### ISSUE TITLE
Screen Sharing crashes aerocord w/ electron 28 x64

### ISSUE THREAD

**Issue by axeltechtips** [AiekDev/aerocord#1]
When clicking screenshare, aerocord crashes.
Great work though!

**Comment by AiekDev** [comment]
![image](https://github.com/AiekDev/aerocord/assets/145149166/018839a4-6cf0-418d-9b26-b88f065d1646)
also what os? windows 7?? windows 8??
for now js use the electron 22 builds, ill figure it out eventually
