### ISSUE TITLE
Licensing issues

### ISSUE THREAD

**Issue by Vendicated** [AiekDev/aerocord#2]
it seems you altered the license header in every file:
https://github.com/AiekDev/aerocord/blob/e3667bfb1b6ce9c0a5f7994f1afd177afa0ec9b1/src/main/autoStart.ts#L1-L5

that's not valid. you must keep original copyright notices intact. "Credits to [x]" is not correcr attribution.

Please fix it. For example, you could use the following:
```js
/*
 * SPDX-License-Identifier: GPL-3.0
 * Modified for Aerocord, originally part of Vesktop, a desktop app aiming to give you a snappier Discord Experience
 * Copyright (c) 2024 YourName
 * Copyright (c) 2023 Vendicated and Vencord contributors
 */
```

**Comment by AiekDev** [comment]
1. i will
2. the actual aerocord repo is here: https://git.randomserver.top/aiek/aerocord so dont expect me to update anything on github

**Comment by Vendicated** [comment]
either fix or delete the github repo.

**Comment by AiekDev** [comment]
there you go. ❤️ 🥰 😘  i luv u bro :))))))))0 <333333

**Comment by Vendicated** [comment]
it seems you haven't made the requested changes on your gitea mirror. please do or we might have to get in touch with your registrar or hosting provider over copyright infringement (seems to be godaddy and digitalocean)

thanks winking face smiley

**Comment by AiekDev** [comment]
the fact that you were so pressed about me trolling u a bit is insane :joy: 

if u continue with shit like this i wont update it at all

also fuck u vencord comm cuz ik this will get sent around i hate yall little shits

**Comment by Vendicated** [comment]
i genuinely have no idea what this is about or who you even are, i was just politely asking you to abide with the license like any other person. forks are welcome, as long as they respect everyone's rights! :)

**Comment by AiekDev** [comment]
stop fucking lying 

ok imma write yall vencord mfers a copypaste lemme COOK

i HATE vencord! I hate vendicated dat weird ahh sux vro weird asl tf what does vro even do with his life i hate the fact vro uses electron-updater i hate vro is fucking weird i hate the fact vro doesnt natively support windows 7 vro like tf vro??? @Vendicated im gonna give u my backported e32 builds using my wrapper so u can natively support it vro like tf?????????? its not dat hard vro smfh like just do it vro yeah its old n shit but still u gotta support it vro give justice to the win2k users vro tf just support them infact give the msdos mfers some justice too vendicated u mad weird vro just support it i hate u so much vro

**Comment by amadalusia** [comment]
https://media.discordapp.net/attachments/1213205868338745364/1291512828603142234/caption.gi

**Comment by AiekDev** [comment]
honestly vro after dis wrapper is fully done there would be 0 reasons to NOT stay on windows 7 :sob :pray: 
![img](https://git.randomserver.top/aiek/win7-wrapper/raw/branch/main/with.png)

**Comment by rushiiMachine** [comment]
vee i have to give props to this guy they're a massive fucking skid troll

**Comment by AiekDev** [comment]
>vee i have to give props to this guy they're a massive fucking skid troll
>**skid**?

https://github.com/rushiiMachine/osu-patcher/blob/8096e916edbaf226f1acf1faed9154628db1a047/osu-patcher/Program.cs

this MIGHT be your code vro???? broke ahh ##$$ no moneyz istaywiththemenghez tf dis broke ahh on 
dis rushiimachine nibba broke he need to get on my level vro wit he moneyz$$$$$$$$$$$$$$$ vencord vendicated ahh
hardcoding ahh nibba out here callin me A SKID tf tf das cray homoxie fwah c:/osu/osu

**Comment by AiekDev** [comment]
@Vendicated hello vro i have sent you very nice email vro please respond asap ASAP ROCKY vro
